SolidCP/Database/update_db.sql, SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/VirtualizationServerController2012.cs, SolidCP/Sources/SolidCP.Providers.Base/Virtualization/VirtualMachine.cs, SolidCP/Sources/SolidCP.Providers.TerminalServices.Windows2012/RdsRunspaceExtensions.cs, SolidCP/Sources/SolidCP.Providers.TerminalServices.Windows2012/Windows2012.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/App_LocalResources/RDSServers.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/App_LocalResources/RDSServers.ascx.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/Code/Helpers/RDSHelper.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/OrganizationCreateOrganization.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/OrganizationCreateOrganization.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDSServers.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDSServers.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDSServers.ascx.designer.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/UserAccountDetails.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VdcCreateServer.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VdcCreateServer.ascx.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VpsDetailsGeneral.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VpsDetailsGeneral.ascx.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VdcCreateServer.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VdcCreateServer.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VdcCreateServer.ascx.designer.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsGeneral.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsGeneral.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsGeneral.ascx.designer.cs
[HyperV2012R2+] Ability to configure custom Gateway and DNS for a private network
Optimize RDS-Servers status update
Fix RDS Server Search
Create Organization - add default Organization ID und Name value
[HyperV2012R2+] VPS Details - show current Hyper-V host for admins
WebPortal - Fix interface issue with german language
=> [HyperV2012R2+] Ability to configure custom Gateway and DNS for a private network / RDS-Servers: optimize status update and fix search

SolidCP/Sources/SolidCP.EnterpriseServer.Client/VirtualizationServerProxy2012.cs, SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/VirtualizationServerController2012.cs, SolidCP/Sources/SolidCP.EnterpriseServer/esVirtualizationServer2012.asmx.cs, SolidCP/Sources/SolidCP.WebPortal/App_GlobalResources/SolidCP_Pages.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/App_GlobalResources/SolidCP_SharedResources.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/App_LocalResources/SpaceSettings.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VpsDetailsAddPrivateAddress.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VpsDetailsAddPrivateAddress.ascx.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VpsDetailsNetwork.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/App_LocalResources/VpsDetailsNetwork.ascx.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsAddPrivateAddress.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsAddPrivateAddress.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsAddPrivateAddress.ascx.designer.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsEditConfiguration.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsNetwork.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsNetwork.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsNetwork.ascx.designer.cs
- [HyperV2012R2+] Ability to change Gateway and DNS in VPS configuration (Private Network - Add IP - Change Gateway and DNS)
- Small fixes for german language.
=> [HyperV2012R2+] Ability to change private network Gateway and DNS in VPS configuration

Languages/German/Resources.xml, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/App_LocalResources/SettingsWebPolicy.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/SolidCP.Portal.Modules.csproj
=> German language fix for #24

SolidCP/Database/update_db.sql, SolidCP/Sources/SolidCP.EnterpriseServer.Client/RemoteDesktopServicesProxy.cs, SolidCP/Sources/SolidCP.EnterpriseServer.Code/RemoteDesktopServices/RemoteDesktopServicesController.cs, SolidCP/Sources/SolidCP.EnterpriseServer/esRemoteDesktopServices.asmx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSCollections.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSEditApplicationUsers.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSEditCollection.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSEditCollectionApps.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSEditCollectionSettings.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSEditCollectionUsers.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSEditUserExperience.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSLocalAdmins.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/RDSUserSessions.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/UserControls/RDSCollectionApps.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/UserControls/RDSCollectionUsers.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/UserControls/RDSCollectionUsers.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/RDS/UserControls/RDSCollectionUsers.ascx.designer.cs
[RDS Collections] Portal performance optimize / Add RDS User - Search fix
(If many users in AD then Add RDS User dialog showed up slowly)
=> [RDS Collections] Portal performance optimize / Add RDS User - Search fix

SolidCP/Sources/SolidCP.EnterpriseServer.Code/WebServers/WebServerController.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/WebsitesSSL.ascx.cs
- [LetsEncrypt] Fix for notification email commit: ES.Services.Servers.GetServiceSettings works with admin account only
=> [LetsEncrypt] Fix for notification email commit

SolidCP/Sources/SolidCP.EnterpriseServer.Code/MailCleaner/APIMailCleanerHelper.cs
=> Add logs to MailCleaner API

SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/UserControls/App_LocalResources/MailboxPlanSelector.ascx.de-DE.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/UserControls/App_LocalResources/MailboxPlanSelector.ascx.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/UserControls/MailboxPlanSelector.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/UserControls/MailboxPlanSelector.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/UserControls/MailboxPlanSelector.ascx.designer.cs
- Remove validator from mailbox plan selector - bug with create / remove organization users if no maibox plans are available
=> Remove validator from mailbox plan selector

SolidCP/Database/update_db.sql
=> Fix update_db.sql

SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsGeneral.ascx.cs
Some clients cannot wait for the OS deployment to complete and destroy the server using the Reboot/Reset/etc buttons.
=> [Portal/HyperV2012R2+] Hidden Reboot/Reset/ShutDown/Etc buttons from clients for 15 minutes until OS deployment is complete.

SolidCP/Database/update_db.sql
=> Fix for global search

SolidCP/Sources/SolidCP.WebDavPortal/Controllers/AccountController.cs
[WebDavPortal] Check if user must change password
=> [WebDavPortal] Check if user must change password

SolidCP.WHMCSModule/modules/addons/solidcp_module/hooks.php, SolidCP.WHMCSModule/modules/servers/SolidCP/SolidCP.php
- [SolidCP.WHMCSModule] ClientEdit hook - fix for MFA
- [SolidCP.WHMCSModule] Fix for PHP8
=> SolidCP.WHMCSModule fixes

SolidCP/Database/update_db.sql
Global search - check additional email addresses for any mailbox types (Fix for GetSearchObject stored procedure)
=> Global search - check additional email addresses for any mailbox types

SolidCP.WHMCSModule/modules/addons/solidcp_module/lang/english.php, SolidCP.WHMCSModule/modules/addons/solidcp_module/lang/german.php, SolidCP.WHMCSModule/modules/addons/solidcp_module/lib/addonautomation.php, SolidCP.WHMCSModule/modules/addons/solidcp_module/lib/configurableoptions.php, SolidCP.WHMCSModule/modules/addons/solidcp_module/solidcp_module.php, SolidCP.WHMCSModule/modules/addons/solidcp_module/templates/admin_addon.tpl, SolidCP.WHMCSModule/modules/addons/solidcp_module/templates/admin_configurable.tpl
- [WHMCSModule] Improve usability of the Addon and Configurable Options pages
You can now search for option/addon name and assign this with SolidCP. No need to get whmcs_id manually anymore.
=> [WHMCSModule] Improve usability of the Addon and Configurable Options pages

SolidCP/Database/update_db.sql, SolidCP/Sources/SolidCP.EnterpriseServer.Code/Data/DataProvider.cs, SolidCP/Sources/SolidCP.EnterpriseServer.Code/ExchangeServer/ExchangeServerController.cs, SolidCP/Sources/SolidCP.EnterpriseServer.Code/HostedSolution/OrganizationController.cs, SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/Helpers/PS/PowerShellScript.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/App_LocalResources/OrganizationUserGeneralSettings.ascx.resx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/OrganizationUserGeneralSettings.ascx, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/OrganizationUserGeneralSettings.ascx.designer.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ProviderControls/HyperV2012R2_Settings.ascx
- [Exchange] Mail enabling of public folders - check contacts
- [HyperV2012R2+] Add template variables to custom Powershell scripts
- Contact Information label fixed
#165
=> Exchange / HyperV fixes

Languages/Resources.xml, SolidCP.Installer/Sources/SolidCP.Setup/SolidCP.Setup.csproj
=> Bugfix in Installer build

SolidCP/Sources/SolidCP.Web.Clients/AssemblyLoader.cs, SolidCP/Sources/SolidCP.WebPortal/Web.config
=> CoreWCF Bugfixes

SolidCP/Sources/SolidCP.WebPortal/Code/PortalAntiXSS.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/ExchangeCreateMailbox.ascx.cs
Fix for 96637d1 - wrong domain regex
=> Fix for 96637d1

SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/ExchangeCreateJournalingMailbox.ascx.cs, SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/ExchangeJournalingMailboxGeneralSettings.ascx.cs
- [Exchange] Add shared mailboxes to journaling recipients
=> [Exchange] Add shared mailboxes to journaling recipients

SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/HardDriveHelper.cs
=> [HyperV] Fix for #212 (Additional VHDX bug)

SolidCP.Installer/Sources/SolidCP.UniversalInstaller.Core/UI/ConsoleUI/ConsoleUI.cs, SolidCP.Installer/Sources/SolidCP.UniversalInstaller.UI.WinForms/SolidCP.UniversalInstaller.UI.WinForms.csproj
Fixed Updater.exe EmbeddedResource in UniversalInstaller.UI.WinForms
=> Fixed build bug

SolidCP.Installer/Sources/SolidCP.UniversalInstaller.Core/Installers/Installer.Main.cs, SolidCP.Installer/Sources/SolidCP.UniversalInstaller.Msi/SolidCP.UniversalInstaller.Msi.vdproj, SolidCP/Sources/SolidCP.Providers.Web.IIS70/IIs70.cs, SolidCP/Sources/SolidCP.Providers.Web.IIs100/IIs100.cs, SolidCP/Sources/SolidCP.Providers.Web.IIs60/IIs60.cs, SolidCP/Sources/SolidCP.Providers.Web.IIs80/IIs80.cs, SolidCP/build.xml
=> Fixed bugs in Installer
