- SolidCP/Sources/SolidCP.Providers.DNS.SimpleDNS80/SimpleDNS8.cs
Make sure DNSSec and raw SOA records are not visible in the DNS editor, so users cannot tamper with them.
> [SimpleDNS80] Fix for DNSSec and SOA record visibility

- Languages/Resources.xml
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/WebServers/WebServerController.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/App_LocalResources/SettingsWebPolicy.ascx.resx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/SettingsWebPolicy.ascx
Enhancement to allow [DOMAIN] and [HOST] variables to be used when specifying web site folder paths in Web Policy Settings.
- Works when creating a new website.
- Works for importing sites that follow the pattern host.domain.tld or host.domain.sld.tld
- When importing, assumes the first part is the host name ("www") and the remainder is the domain ("domain.co.uk").  If there is no host part then it will treat the domain as the host which will be wrong. Short of maintaining a full list of all .sld.tld combinations, no way to make this 100% foolproof.
Fixes # N/A
-  Manually Tested
-  Built code to ensure it has no errors
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings
> Added [DOMAIN] and [HOST] variables to Web Policy.

- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Users/UserController.cs
- SolidCP/Sources/SolidCP.EnterpriseServer/esUsers.asmx.cs
Enhanced the AddUser API to allow notes to be added to customers account at the time of account creation. An optional string array can be provided where each string is added as a separate note to the customers account.
The User entity has a comments field which appears to have been depreciated in favour of using the customer notes functionality. The Enterprise Server API for creating users had not been updated for this scenario. 
Tested locally.
- [X ] Built code to ensure it has no errors
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
> Modified AddUser API to allow optional notes to be added when creating a user

- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/VirtualizationServerController2012.cs
Gives a description of the error for Third party services if they use SOAP. At this moment if we pass a wrong osTemplateFile, we don't know why a creating VM crashing
> [HyperVController2012] - added an exception if osTemplateFile was not found

- SolidCP/Sources/SolidCP.Providers.TerminalServices.Windows2012/Windows2012.cs
The NetBios domain is "calculated" instead of being fetched with the already existing function call which always gives the correct answer.
> fix issue where shortdomain is sometimes wrongly determined

- SolidCP/Sources/SolidCP.EnterpriseServer.Code/HostedSolution/OrganizationController.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ProviderControls/App_LocalResources/Organizations_Settings.ascx.de-DE.resx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ProviderControls/App_LocalResources/Organizations_Settings.ascx.resx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ProviderControls/Organizations_Settings.ascx
Currently there are two username pattern.
The standard pattern uses the name and always appended with a long counter.
At first you think that the user is never confronted with that username. But that is not true. It pops up in various places in the communication to the customer (can't remember where)
I hated that so much that I took the time to create another one.
I uses the name and only appends a short counter if needed.
> Added new Username pattern

- SolidCP.WHMCSModule/modules/addons/solidcp_module/lib/configurableoptions.php
solidcp_configurable.whmcs_id should be connected to tblproductconfigoptionssub.id
One configurable option (tblproductconfigoptions) can have multiple sub-options (tblproductconfigoptionssub) (if it's a dropdown or radio button) and each sub-option must then be linked to SolidCP and not just whole configurable option.
https://solidcp.com/forum/question/whmcs-and-configurable-options-names-not-displaying/
> [WHMCS Module] Fix for getConfigurableOptions

- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VdcCreateServer.ascx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsEditConfiguration.ascx.cs
[HyperV2012R2+] Fix for additional HDDs and unlimited quota (7ab03e8)
A negative number is displayed when the quota is unlimited and a new HDD is added
> [HyperV2012R2+] Fix for additional HDDs and unlimited quota (7ab03e8)

- Languages/Resources.xml
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/Helpers/VM/IpAddressExternalHelper.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/Helpers/VM/IpAddressPrivateHelper.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/UseCase/ChangeVirtualMachineAdministratorPasswordHandler.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/UseCase/ChangeVirtualMachineStateHandler.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/UseCase/DeleteVirtualMachineHandler.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/UseCase/UpdateVirtualMachineHostNameHandler.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/UseCase/UpdateVirtualMachineResourceHandler.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/VirtualizationServerController2012.cs
- SolidCP/Sources/SolidCP.WebPortal/App_GlobalResources/SolidCP_SharedResources.ascx.ar-AE.resx
- SolidCP/Sources/SolidCP.WebPortal/App_GlobalResources/SolidCP_SharedResources.ascx.de-DE.resx
- SolidCP/Sources/SolidCP.WebPortal/App_GlobalResources/SolidCP_SharedResources.ascx.resx
The logs were recorded to nowhere because was a wrong tag.
> [HyperV2012R2+] Fixed incorrect recording events in Audit log.

- SolidCP/Database/update_db.sql
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Packages/PackageAsyncWorker.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Servers/ServerController.cs
- SolidCP/Sources/SolidCP.EnterpriseServer/esPackages.asmx.cs
**Fix for DeletePackage** - if you delete a user with an existing hosting space, IPs and private network VLANs are not reallocated to the parent space - fixed
**[HyperV2012R2+] Allocate IPs & VLANs with not assigned server** - you can create a large pool of IPs and private network VLANs with no assigned server. All servers can use these IPs & VLANs
> Fix for DeletePackage / [HyperV2012R2+] Allocate IPs & VLANs with not assigned server

- SolidCP/Database/update_db.sql
[SQL] GetSearchObject - wrong join fixed
Wrong mailboxes could be displayed in global search
> [SQL] GetSearchObject - wrong join fixed

- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/Login.ascx
Changes the pin entry form so the login button is first in the page code before the "Resend Pin Code" button.
The two column layout is changed to a 1 column layout for the buttons so the Login button floats right when added in front of the Resend Pin Code button.
This allows the user to press the enter key after PIN entry and login instead of resending the PIN code.
Fixes #136 
Tested in Chrome:
Tested in Firefox:
> Fix issue #136

- SolidCP/Database/update_db.sql
- SolidCP/Sources/SolidCP.EnterpriseServer.Base/System/SystemSettings.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Client/UsersProxy.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Data/DataProvider.cs
- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Users/UserController.cs
- SolidCP/Sources/SolidCP.EnterpriseServer/esUsers.asmx.cs
- SolidCP/Sources/SolidCP.WebPortal/App_GlobalResources/SolidCP_SharedResources.ascx.de-DE.resx
- SolidCP/Sources/SolidCP.WebPortal/Code/PortalUtils.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/App_LocalResources/Login.ascx.de-DE.resx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/App_LocalResources/SystemSettings.ascx.resx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/LoggedUserEditDetails.ascx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/Login.ascx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/Login.ascx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/Login.ascx.designer.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/PeersEditPeer.ascx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/SkinControls/SignedInUser.ascx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/SystemSettings.ascx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/SystemSettings.ascx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/SystemSettings.ascx.designer.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/UserAccountEditDetails.ascx.cs
The following enhancements / fixes have been implemented:
1. If the user generates the confirmation code via the app, an e-mail is no longer sent. It is also not possible to send it again during login.
2. If a user does not have the "right" to change MFA Mode, the checkbox is deactivated.
3. In the system settings, it is possible to prohibit peer logins from changing their MFA mode.
4. In the system settings, it is possible to change the display name used in the authenticator app. The default is SolidCP.
5. In the upper right corner the username of the currently logged in user is displayed.
> Mfa fixes + improvements

- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/OrganizationUserGeneralSettings.ascx.cs
Send password reset request for existing users
If you enable the password reset Link in System Settings -> Cloud storage portal settings, you can send a password reset email for a new users. However, this didn't work for existing users.
> Send password reset request for existing users

- SolidCP/Sources/SolidCP.WebDavPortal/Scripts/appScripts/SCP-webdav.js
[WebDavPortal] Fix "Please wait" dialog hang up if browser page back button pressed
Sometimes the "Please wait..." modal hangs when you go into a folder and then press the back button in the browser.
> [WebDavPortal] Fix "Please wait" dialog hang up

- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/OrganizationUserGeneralSettings.ascx.cs
Fix for 96637d1 - TextBox doesn't run HTML, JavaScript etc., but Literal does..
> [Exchange] Use PortalAntiXSS.Encode for litDisplayName (fix for 96637d1)

- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/VPS2012/VpsDetailsEditConfiguration.ascx.cs
DMZ network VLAN could be removed from the database when some VM settings were changed
> [HyperV] DMZ VLAN will be removed from DB when settings changed - fixed

- SolidCP.Installer/Sources/Setup.WIX/Product.wxs
- SolidCP.Installer/Sources/Setup.WIXInstaller/Product.wxs
- SolidCP.Installer/Sources/SolidCP.Installer.Core/Common/FileUtils.cs
- SolidCP.Installer/Sources/SolidCP.Installer.Core/Loader.cs
- SolidCP.Installer/Sources/SolidCP.Installer/Controls/ComponentControl.cs
- SolidCP.Installer/Sources/SolidCP.Installer/Controls/Loader.cs
- SolidCP.Installer/Sources/SolidCP.Setup/Common/SqlProcess.cs
Starting from SolidCP version 1.4.8, the updater was broken, especially for Enterprise Server. This caused incomplete database updates and broke the IIS pool, leading to an unexplained 503 error. The issue could be fixed by restarting the server and manually running the **update_db.sql**.
The problem was likely caused by an empty character being accidentally added to the **update_db.sql** file in version 1.4.9, which broke the update process.
Fixed this issue:
```
System.Exception: Can't run SQL script C:\Program Files (x86)\SolidCP Installer\Tmp\setup\update_db.sql ---> System.Exception: Error executing SQL command:  ---> System.InvalidOperationException: ExecuteNonQuery: CommandText property has not been initialized
at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, …
```
> [Installer] Add partial offline installer and fix SQL update fatal error

- SolidCP/Sources/SolidCP.Providers.Base/SolidCP.Providers.Base.csproj
- SolidCP/Sources/SolidCP.Providers.Base/Virtualization/CimSessionMode.cs
- SolidCP/Sources/SolidCP.Providers.Base/Virtualization/SummaryInformationRequest.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Data/VirtualMachineData.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Extensions/PSObjectExtension.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/BiosHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/DvdDriveHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/FileSystemHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/HardDriveHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/JobHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/MemoryHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/NetworkAdapterHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/ReplicaHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/SnapshotHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/VdsHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/VirtualMachineHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/HyperV2012R2.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/MiManager.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/PowerShellManager.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/SolidCP.Providers.Virtualization.HyperV2012R2.csproj
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Wmi.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2019/SolidCP.Providers.Virtualization.HyperV2019.csproj
- SolidCP/Sources/SolidCP.Server/VirtualizationServer2012.asmx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ProviderControls/HyperV2012R2_Settings.ascx
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ProviderControls/HyperV2012R2_Settings.ascx.cs
- SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ProviderControls/HyperV2012R2_Settings.ascx.designer.cs
This PR is related to issue #224 and aims to optimize Hyper-V performance on high-load nodes. On average, performance will improve by about 2x, and in some cases, up to 6x. On nodes with fewer than 100 servers, there may be no noticeable changes, except for a more responsive control panel when working with VMs.
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/windows-management-infrastructure
Unlike WMI, MI/CIM supports not only DCom but also the modern DSMan:
https://support.quest.com/kb/4311903/comparison-between-dcom-wmi-and-winrm-technologies
By default, MI uses DCom for Remote Hyper-V. This can be changed in the Provider Settings.
Example PowerShell:
```powershell
Get-VM -Id 'VM_ID' | Select-Object -Property Id, Name, State
```
C#
```csharp
var commands = …
```
> [HyperV2012R2+] Refactor for performance

- SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/Helpers/VirtualMachineHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/Helpers/HardDriveHelper.cs
- SolidCP/Sources/SolidCP.Providers.Virtualization.HyperV-2012R2/HyperV2012R2.cs
If VM or VHDX path was changed on the HyperV, then the data in the database remains inconsistent. This PR checks and updates the data when the VM is opened in SolidCP. Even if a VHDX was added directly in HyperV, it will be automatically assigned in SolidCP later.
The PR should not affect performance if the data is already up to date.
> [HyperV] Check and update the VM RootFolderPath and VirtualHardDrivePath in the database

- README.md
- SolidCP/Sources/SolidCP.Providers.Mail.SmarterMail100/SolidCP.Providers.Mail.SmarterMail100.csproj
- Fixed build error
- Removed .NET Framework References in SmarterMail100.csproj
- SmarterMail100 should now run on Linux too
> Fixed build error & Removed net48 references in SmarterMail100
